[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# VITE_STRIPE_PUBLISHABLE_KEY = "pk_live_your_stripe_key"
# VITE_SUPABASE_URL = "https://your-project.supabase.co"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
# VITE_APP_URL = "https://your-domain.com"